from datetime import datetime, timedelta, timezone

MOVIES = [
    {
        "tmdbId": 986056,
        "title": "Thunderbolts*",
        "poster": "https://image.tmdb.org/t/p/w500/m9EtP1Yrzv6v7dMaC9mRaGhd1um.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/8eifdha9GQeZAkexgtD45546XKx.jpg",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "releaseDate": "2025-05-02",
        "rating": 7.3,
        "popularity": 96,
        "overview": "A team of antiheroes is pulled into a dangerous mission that tests loyalty, power, and redemption.",
        "streaming": ["Disney+"],
        "blurayAvailable": True,
    },
    {
        "tmdbId": 1234821,
        "title": "Jurassic World Rebirth",
        "poster": "https://image.tmdb.org/t/p/w500/q0fGCmjLu42MPlSO9OYWpI5w86I.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/7Zx3wDG5bBtcfk8lcnCWDOLM4Y4.jpg",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "releaseDate": "2025-07-02",
        "rating": 6.9,
        "popularity": 93,
        "overview": "A new expedition enters an isolated equatorial zone to recover genetic material from colossal species.",
        "streaming": ["Peacock", "Prime Video"],
        "blurayAvailable": True,
    },
    {
        "tmdbId": 950387,
        "title": "A Minecraft Movie",
        "poster": "https://image.tmdb.org/t/p/w500/yFHHfHcUgGAxziP1C3lLt0q2T4s.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg",
        "genres": ["Adventure", "Comedy", "Family"],
        "releaseDate": "2025-04-04",
        "rating": 6.4,
        "popularity": 91,
        "overview": "Four misfits are pulled through a portal into a cubic world powered by imagination and survival.",
        "streaming": ["Max"],
        "blurayAvailable": True,
    },
    {
        "tmdbId": 617126,
        "title": "The Fantastic Four: First Steps",
        "poster": "https://image.tmdb.org/t/p/w500/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/zOpe0eHsq0A2NvNyBbtT6sj53qV.jpg",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "releaseDate": "2025-07-25",
        "rating": 7.1,
        "popularity": 90,
        "overview": "Marvel's first family faces cosmic pressure while trying to remain a family.",
        "streaming": ["Disney+"],
        "blurayAvailable": False,
    },
    {
        "tmdbId": 575265,
        "title": "Mission: Impossible - The Final Reckoning",
        "poster": "https://image.tmdb.org/t/p/w500/z53D72EAOxGRqdr7KXXWp9dJiDe.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/3VkPqpjKikQgEl5wGKlAqzmk0E5.jpg",
        "genres": ["Action", "Thriller"],
        "releaseDate": "2025-05-23",
        "rating": 7.8,
        "popularity": 88,
        "overview": "Ethan Hunt returns for a final mission with impossible stakes.",
        "streaming": ["Paramount+"],
        "blurayAvailable": True,
    },
    {
        "tmdbId": 872585,
        "title": "Oppenheimer",
        "poster": "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
        "genres": ["Drama", "History"],
        "releaseDate": "2023-07-21",
        "rating": 8.1,
        "popularity": 82,
        "overview": "A physicist leads the Manhattan Project and faces the moral gravity of invention.",
        "streaming": ["Peacock"],
        "blurayAvailable": True,
    },
    {
        "tmdbId": 346698,
        "title": "Barbie",
        "poster": "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg",
        "genres": ["Comedy", "Fantasy"],
        "releaseDate": "2023-07-21",
        "rating": 7.0,
        "popularity": 79,
        "overview": "Barbie journeys from a perfect plastic world into a messier, stranger real one.",
        "streaming": ["Max"],
        "blurayAvailable": True,
    },
    {
        "tmdbId": 693134,
        "title": "Dune: Part Two",
        "poster": "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
        "genres": ["Adventure", "Drama", "Sci-Fi"],
        "releaseDate": "2024-03-01",
        "rating": 8.3,
        "popularity": 86,
        "overview": "Paul Atreides unites with Chani and the Fremen while seeking revenge and avoiding a terrible future.",
        "streaming": ["Max"],
        "blurayAvailable": True,
    },
    {
        "tmdbId": 1022789,
        "title": "Inside Out 2",
        "poster": "https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg",
        "genres": ["Animation", "Comedy", "Family"],
        "releaseDate": "2024-06-14",
        "rating": 7.6,
        "popularity": 84,
        "overview": "Riley's mind welcomes new emotions during the chaos of becoming a teenager.",
        "streaming": ["Disney+"],
        "blurayAvailable": True,
    },
    {
        "tmdbId": 912649,
        "title": "Venom: The Last Dance",
        "poster": "https://image.tmdb.org/t/p/w500/aosm8NMQ3UyoBVpSxyimorCQykC.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/3V4kLQg0kSqPLctI5ziYWabAZYF.jpg",
        "genres": ["Action", "Sci-Fi", "Thriller"],
        "releaseDate": "2024-10-25",
        "rating": 6.6,
        "popularity": 77,
        "overview": "Eddie and Venom are hunted by forces from both worlds.",
        "streaming": ["Netflix"],
        "blurayAvailable": True,
    },
    {
        "tmdbId": 533535,
        "title": "Deadpool & Wolverine",
        "poster": "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
        "genres": ["Action", "Comedy", "Sci-Fi"],
        "releaseDate": "2024-07-26",
        "rating": 7.8,
        "popularity": 89,
        "overview": "Deadpool pulls Wolverine into a multiverse mission that gets violent, chaotic, and weird fast.",
        "streaming": ["Disney+"],
        "blurayAvailable": True,
    },
    {
        "tmdbId": 786892,
        "title": "Furiosa: A Mad Max Saga",
        "poster": "https://image.tmdb.org/t/p/w500/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/6s0fxdK8y3B8If9vM6W0lP5rA2X.jpg",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "releaseDate": "2024-05-24",
        "rating": 7.6,
        "popularity": 78,
        "overview": "Furiosa survives a brutal wasteland war while fighting to return home.",
        "streaming": ["Max"],
        "blurayAvailable": True,
    },
    {
        "tmdbId": 1184918,
        "title": "The Wild Robot",
        "poster": "https://image.tmdb.org/t/p/w500/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/6s0fxdK8y3B8If9vM6W0lP5rA2X.jpg",
        "genres": ["Animation", "Adventure", "Family"],
        "releaseDate": "2024-09-27",
        "rating": 8.2,
        "popularity": 83,
        "overview": "A service robot stranded on a wild island learns to survive among animals and found family.",
        "streaming": ["Peacock"],
        "blurayAvailable": True,
    },
    {
        "tmdbId": 653346,
        "title": "Kingdom of the Planet of the Apes",
        "poster": "https://image.tmdb.org/t/p/w500/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/4woSOUD0equAYzvwhWBHIJDCM88.jpg",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "releaseDate": "2024-05-10",
        "rating": 7.1,
        "popularity": 76,
        "overview": "A young ape must decide what kind of future will be built long after Caesar's era.",
        "streaming": ["Hulu"],
        "blurayAvailable": True,
    },
    {
        "tmdbId": 945961,
        "title": "Alien: Romulus",
        "poster": "https://image.tmdb.org/t/p/w500/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg",
        "genres": ["Horror", "Sci-Fi", "Thriller"],
        "releaseDate": "2024-08-16",
        "rating": 7.2,
        "popularity": 74,
        "overview": "Young colonists scavenging a derelict station discover the galaxy's most terrifying organism.",
        "streaming": ["Hulu"],
        "blurayAvailable": True,
    },
    {
        "tmdbId": 1241982,
        "title": "Moana 2",
        "poster": "https://image.tmdb.org/t/p/w500/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg",
        "genres": ["Animation", "Adventure", "Family"],
        "releaseDate": "2024-11-27",
        "rating": 7.0,
        "popularity": 85,
        "overview": "Moana answers a new call from her ancestors and sails toward dangerous uncharted waters.",
        "streaming": ["Disney+"],
        "blurayAvailable": True,
    },
    {
        "tmdbId": 939243,
        "title": "Sonic the Hedgehog 3",
        "poster": "https://image.tmdb.org/t/p/w500/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/zOpe0eHsq0A2NvNyBbtT6sj53qV.jpg",
        "genres": ["Action", "Adventure", "Family"],
        "releaseDate": "2024-12-20",
        "rating": 7.3,
        "popularity": 81,
        "overview": "Sonic, Tails, and Knuckles face their fastest and most dangerous rival yet.",
        "streaming": ["Paramount+"],
        "blurayAvailable": True,
    },
    {
        "tmdbId": 762509,
        "title": "Mufasa: The Lion King",
        "poster": "https://image.tmdb.org/t/p/w500/lurEK87kukWNaHd0zYnsi3yzJrs.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/7Zx3wDG5bBtcfk8lcnCWDOLM4Y4.jpg",
        "genres": ["Adventure", "Animation", "Drama"],
        "releaseDate": "2024-12-20",
        "rating": 6.9,
        "popularity": 73,
        "overview": "Rafiki tells the story of Mufasa's rise from orphaned cub to legendary king.",
        "streaming": ["Disney+"],
        "blurayAvailable": True,
    },
    {
        "tmdbId": 823464,
        "title": "Godzilla x Kong: The New Empire",
        "poster": "https://image.tmdb.org/t/p/w500/tMefBSflR6PGQLv7WvFPpKLZkyk.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/oe7mWkvYhK4PLRNAVSvonzyUXNy.jpg",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "releaseDate": "2024-03-29",
        "rating": 6.6,
        "popularity": 75,
        "overview": "Godzilla and Kong face a hidden threat that could change the balance of the Hollow Earth.",
        "streaming": ["Max"],
        "blurayAvailable": True,
    },
    {
        "tmdbId": 1029575,
        "title": "The Fall Guy",
        "poster": "https://image.tmdb.org/t/p/w500/aBkqu7EddWK7qmY4grL4I6edx2h.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/1pmXyN3sKeYoUhu5VBZiDU4BX21.jpg",
        "genres": ["Action", "Comedy", "Romance"],
        "releaseDate": "2024-05-03",
        "rating": 7.0,
        "popularity": 68,
        "overview": "A battered stuntman gets pulled into a missing-person mystery on a blockbuster set.",
        "streaming": ["Peacock"],
        "blurayAvailable": True,
    },
    {
        "tmdbId": 1063879,
        "title": "Paddington in Peru",
        "poster": "https://media.themoviedb.org/t/p/w500/dY98PkUAbIGUUg0FhXEcOkbzHIZ.jpg",
        "backdrop": "https://media.themoviedb.org/t/p/w780/k0ucFBBgSDTXYU8fVHXJyjAuIIe.jpg",
        "genres": ["Adventure", "Comedy", "Family"],
        "releaseDate": "2025-01-17",
        "rating": 7.4,
        "popularity": 67,
        "overview": "Paddington returns to Peru for a family adventure that turns unexpectedly dangerous.",
        "streaming": ["Netflix"],
        "blurayAvailable": True,
    },
]

TV_SHOWS = [
    {
        "tmdbId": 1399,
        "title": "Game of Thrones",
        "originalTitle": "Game of Thrones",
        "poster": "https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
        "genres": ["Drama", "Fantasy"],
        "firstAirDate": "2011-04-17",
        "rating": 8.4,
        "popularity": 95,
        "overview": "Noble families fight for control of Westeros while an ancient threat rises in the north.",
        "mediaType": "tv",
    },
    {
        "tmdbId": 1396,
        "title": "Breaking Bad",
        "originalTitle": "Breaking Bad",
        "poster": "https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
        "genres": ["Drama", "Crime"],
        "firstAirDate": "2008-01-20",
        "rating": 8.9,
        "popularity": 90,
        "overview": "A chemistry teacher turns to meth production after a devastating diagnosis.",
        "mediaType": "tv",
    },
    {
        "tmdbId": 87108,
        "title": "Cobra Kai",
        "originalTitle": "Cobra Kai",
        "poster": "https://image.tmdb.org/t/p/w500/6GDW4EsgsXlYrL1ASb5eCHQK4er.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/kOeVCGWqM4UXyKL3W4cM7i6otRB.jpg",
        "genres": ["Action", "Comedy", "Drama"],
        "firstAirDate": "2018-05-02",
        "rating": 8.2,
        "popularity": 84,
        "overview": "Decades after the All Valley Tournament, old rivals reignite a karate feud.",
        "mediaType": "tv",
    },
    {
        "tmdbId": 94997,
        "title": "House of the Dragon",
        "originalTitle": "House of the Dragon",
        "poster": "https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
        "genres": ["Drama", "Fantasy"],
        "firstAirDate": "2022-08-21",
        "rating": 8.4,
        "popularity": 88,
        "overview": "The Targaryen civil war begins long before Daenerys, with dragons and succession on the line.",
        "mediaType": "tv",
    },
    {
        "tmdbId": 76479,
        "title": "The Boys",
        "originalTitle": "The Boys",
        "poster": "https://image.tmdb.org/t/p/w500/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/5DUMPBSnHOZsbBv81GFXZXvDpo6.jpg",
        "genres": ["Action", "Sci-Fi", "Comedy"],
        "firstAirDate": "2019-07-25",
        "rating": 8.4,
        "popularity": 87,
        "overview": "A group of vigilantes targets corrupt superheroes and the company protecting them.",
        "mediaType": "tv",
    },
    {
        "tmdbId": 85552,
        "title": "Euphoria",
        "originalTitle": "Euphoria",
        "poster": "https://image.tmdb.org/t/p/w500/jtnfNzqZwN4E32FGGxx1YZaBWWf.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/oKt4J3TFjWirVwBqoHyIvv5IImd.jpg",
        "genres": ["Drama"],
        "firstAirDate": "2019-06-16",
        "rating": 8.3,
        "popularity": 79,
        "overview": "Teenagers struggle with identity, addiction, and relationships in a hyper-stylized suburbia.",
        "mediaType": "tv",
    },
    {
        "tmdbId": 60625,
        "title": "Rick and Morty",
        "originalTitle": "Rick and Morty",
        "poster": "https://image.tmdb.org/t/p/w500/gdIrmf2DdY5mgN6ycVP0XlzKzbE.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/eV3XnUul4UfIivz3kxgeIozeo50.jpg",
        "genres": ["Animation", "Comedy", "Sci-Fi"],
        "firstAirDate": "2013-12-02",
        "rating": 8.7,
        "popularity": 76,
        "overview": "A reckless scientist drags his grandson through absurd and dangerous multiverse adventures.",
        "mediaType": "tv",
    },
    {
        "tmdbId": 66732,
        "title": "Stranger Things",
        "originalTitle": "Stranger Things",
        "poster": "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
        "genres": ["Drama", "Fantasy", "Sci-Fi"],
        "firstAirDate": "2016-07-15",
        "rating": 8.6,
        "popularity": 86,
        "overview": "A small town uncovers secret experiments, supernatural forces, and one very unusual girl.",
        "mediaType": "tv",
    },
    {
        "tmdbId": 82856,
        "title": "The Bear",
        "originalTitle": "The Bear",
        "poster": "https://image.tmdb.org/t/p/w500/sHFlbKS3WLqMnp9t2ghADIJFnuQ.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/9vN6DHB6d0v2cB8Kx6pGkrbdOND.jpg",
        "genres": ["Comedy", "Drama"],
        "firstAirDate": "2022-06-23",
        "rating": 8.3,
        "popularity": 72,
        "overview": "A young chef returns to Chicago to run his family sandwich shop under intense pressure.",
        "mediaType": "tv",
    },
    {
        "tmdbId": 71912,
        "title": "The Witcher",
        "originalTitle": "The Witcher",
        "poster": "https://image.tmdb.org/t/p/w500/cZ0d3rtvXPVvuiX22sP79K3Hmjz.jpg",
        "backdrop": "https://image.tmdb.org/t/p/w780/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg",
        "genres": ["Action", "Adventure", "Fantasy"],
        "firstAirDate": "2019-12-20",
        "rating": 8.0,
        "popularity": 74,
        "overview": "A monster hunter, a sorceress, and a princess become linked by destiny on a dangerous continent.",
        "mediaType": "tv",
    },
]

MOVIES.extend(
    [
        {
            "tmdbId": 603692,
            "title": "John Wick: Chapter 4",
            "poster": "https://media.themoviedb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/7I6VUdPj6tQECNHdviJkUHD2u89.jpg",
            "genres": ["Action", "Thriller"],
            "releaseDate": "2023-03-24",
            "rating": 7.7,
            "popularity": 72,
            "overview": "John Wick fights through the High Table's deadliest gauntlet in a globe-spanning final stand.",
            "streaming": ["Starz", "Peacock"],
            "blurayAvailable": True,
        },
        {
            "tmdbId": 157336,
            "title": "Interstellar",
            "poster": "https://media.themoviedb.org/t/p/w500/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/2ssWTSVklAEc98frZUQhgtGHx7s.jpg",
            "genres": ["Adventure", "Drama", "Sci-Fi"],
            "releaseDate": "2014-11-07",
            "rating": 8.4,
            "popularity": 66,
            "overview": "A desperate space mission searches for a new home as Earth collapses under ecological ruin.",
            "streaming": ["Paramount+"],
            "blurayAvailable": True,
        },
        {
            "tmdbId": 27205,
            "title": "Inception",
            "poster": "https://media.themoviedb.org/t/p/w500/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
            "genres": ["Action", "Sci-Fi", "Thriller"],
            "releaseDate": "2010-07-16",
            "rating": 8.4,
            "popularity": 64,
            "overview": "A thief who steals secrets through dreams is offered one impossible job: plant an idea instead.",
            "streaming": ["Netflix"],
            "blurayAvailable": True,
        },
        {
            "tmdbId": 361743,
            "title": "Top Gun: Maverick",
            "poster": "https://media.themoviedb.org/t/p/w500/n0YuM4f5lvGAP6MAW2kBIzugXnc.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg",
            "genres": ["Action", "Drama"],
            "releaseDate": "2022-05-27",
            "rating": 8.3,
            "popularity": 71,
            "overview": "Maverick trains a new generation of pilots for a mission that demands everything he has left.",
            "streaming": ["Paramount+"],
            "blurayAvailable": True,
        },
        {
            "tmdbId": 447365,
            "title": "Guardians of the Galaxy Vol. 3",
            "poster": "https://media.themoviedb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg",
            "genres": ["Action", "Adventure", "Sci-Fi"],
            "releaseDate": "2023-05-05",
            "rating": 7.9,
            "popularity": 70,
            "overview": "The Guardians rally to save Rocket and keep their found family from falling apart.",
            "streaming": ["Disney+"],
            "blurayAvailable": True,
        },
        {
            "tmdbId": 569094,
            "title": "Spider-Man: Across the Spider-Verse",
            "poster": "https://media.themoviedb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/9xfDWXAUbFXQK585JvByT5pEAhe.jpg",
            "genres": ["Animation", "Action", "Sci-Fi"],
            "releaseDate": "2023-06-02",
            "rating": 8.5,
            "popularity": 74,
            "overview": "Miles Morales is thrown across the multiverse and forced to choose what kind of Spider-Man he wants to be.",
            "streaming": ["Netflix"],
            "blurayAvailable": True,
        },
        {
            "tmdbId": 502356,
            "title": "The Super Mario Bros. Movie",
            "poster": "https://media.themoviedb.org/t/p/w500/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg",
            "genres": ["Animation", "Adventure", "Family"],
            "releaseDate": "2023-04-05",
            "rating": 7.1,
            "popularity": 69,
            "overview": "Mario and Luigi tumble into the Mushroom Kingdom and race to stop Bowser's takeover.",
            "streaming": ["Peacock"],
            "blurayAvailable": True,
        },
        {
            "tmdbId": 466420,
            "title": "Killers of the Flower Moon",
            "poster": "https://media.themoviedb.org/t/p/w500/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/1X7vow16X7CnCoexXh4H4F2yDJv.jpg",
            "genres": ["Crime", "Drama", "History"],
            "releaseDate": "2023-10-20",
            "rating": 7.6,
            "popularity": 58,
            "overview": "A series of murders in the Osage Nation exposes a conspiracy rooted in greed and power.",
            "streaming": ["Apple TV+"],
            "blurayAvailable": True,
        },
        {
            "tmdbId": 667538,
            "title": "Transformers: Rise of the Beasts",
            "poster": "https://media.themoviedb.org/t/p/w500/gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/2vFuG6bWGyQUzYS9d69E5l85nIz.jpg",
            "genres": ["Action", "Adventure", "Sci-Fi"],
            "releaseDate": "2023-06-09",
            "rating": 7.0,
            "popularity": 57,
            "overview": "Optimus Prime teams with the Maximals to face a planet-level cosmic threat.",
            "streaming": ["Paramount+"],
            "blurayAvailable": True,
        },
        {
            "tmdbId": 385687,
            "title": "Fast X",
            "poster": "https://media.themoviedb.org/t/p/w500/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
            "genres": ["Action", "Crime", "Thriller"],
            "releaseDate": "2023-05-19",
            "rating": 6.8,
            "popularity": 60,
            "overview": "Dom Toretto's family is pushed to the brink by a revenge plot years in the making.",
            "streaming": ["Peacock"],
            "blurayAvailable": True,
        },
        {
            "tmdbId": 155,
            "title": "The Dark Knight",
            "poster": "https://media.themoviedb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg",
            "genres": ["Action", "Crime", "Drama"],
            "releaseDate": "2008-07-18",
            "rating": 8.5,
            "popularity": 62,
            "overview": "Batman faces the Joker as Gotham is pushed into chaos and moral collapse.",
            "streaming": ["Max"],
            "blurayAvailable": True,
        },
        {
            "tmdbId": 680,
            "title": "Pulp Fiction",
            "poster": "https://media.themoviedb.org/t/p/w500/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
            "genres": ["Crime", "Drama"],
            "releaseDate": "1994-10-14",
            "rating": 8.5,
            "popularity": 55,
            "overview": "Intersecting criminal stories unfold across Los Angeles with violence, humor, and style.",
            "streaming": ["Paramount+"],
            "blurayAvailable": True,
        },
        {
            "tmdbId": 13,
            "title": "Forrest Gump",
            "poster": "https://media.themoviedb.org/t/p/w500/Cw4hIUIAmSYfK9QfaUW5igp9La.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg",
            "genres": ["Drama", "Romance"],
            "releaseDate": "1994-07-06",
            "rating": 8.4,
            "popularity": 54,
            "overview": "An unexpectedly extraordinary man drifts through decades of American history with quiet sincerity.",
            "streaming": ["Paramount+"],
            "blurayAvailable": True,
        },
        {
            "tmdbId": 278,
            "title": "The Shawshank Redemption",
            "poster": "https://media.themoviedb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
            "genres": ["Drama", "Crime"],
            "releaseDate": "1994-09-23",
            "rating": 8.7,
            "popularity": 53,
            "overview": "Hope and friendship endure inside prison walls over decades of hardship and corruption.",
            "streaming": ["Max"],
            "blurayAvailable": True,
        },
        {
            "tmdbId": 238,
            "title": "The Godfather",
            "poster": "https://media.themoviedb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg",
            "genres": ["Crime", "Drama"],
            "releaseDate": "1972-03-24",
            "rating": 8.7,
            "popularity": 52,
            "overview": "The Corleone family navigates violence, legacy, and power in the American underworld.",
            "streaming": ["Paramount+"],
            "blurayAvailable": True,
        },
        {
            "tmdbId": 787699,
            "title": "Wonka",
            "poster": "https://media.themoviedb.org/t/p/w500/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/uIk2g2bRkNwNywKZIhC5oIU94Kh.jpg",
            "genres": ["Comedy", "Family", "Fantasy"],
            "releaseDate": "2023-12-15",
            "rating": 7.2,
            "popularity": 61,
            "overview": "A young Willy Wonka chases his sweetest dreams while battling rivals in the city.",
            "streaming": ["Max"],
            "blurayAvailable": True,
        },
    ]
)

TV_SHOWS.extend(
    [
        {
            "tmdbId": 100088,
            "title": "The Last of Us",
            "originalTitle": "The Last of Us",
            "poster": "https://media.themoviedb.org/t/p/w500/dmo6TYuuJgaYinXBPjrgG9mB5od.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/lY2DhbA7Hy44fAKddr06UrXWWaQ.jpg",
            "genres": ["Drama", "Sci-Fi"],
            "firstAirDate": "2023-01-15",
            "rating": 8.6,
            "popularity": 83,
            "overview": "A hardened smuggler escorts a teenager across a fungal-ravaged America.",
            "mediaType": "tv",
        },
        {
            "tmdbId": 94605,
            "title": "Arcane",
            "originalTitle": "Arcane",
            "poster": "https://media.themoviedb.org/t/p/w500/abf8tHznhSvl9BAElD2cQeRr7do.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg",
            "genres": ["Animation", "Action", "Fantasy"],
            "firstAirDate": "2021-11-06",
            "rating": 8.7,
            "popularity": 82,
            "overview": "Two sisters are torn apart as political unrest and hextech transform twin cities.",
            "mediaType": "tv",
        },
        {
            "tmdbId": 110316,
            "title": "Squid Game",
            "originalTitle": "Squid Game",
            "poster": "https://media.themoviedb.org/t/p/w500/Ac8ruycRXzgcsndTZFK6ouGA0FA.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/QZaPkNUvhdcKONuO2fXuqtcQRo.jpg",
            "genres": ["Drama", "Thriller"],
            "firstAirDate": "2021-09-17",
            "rating": 8.3,
            "popularity": 81,
            "overview": "Desperate contestants risk everything in a deadly tournament built from children's games.",
            "mediaType": "tv",
        },
        {
            "tmdbId": 2316,
            "title": "The Office",
            "originalTitle": "The Office",
            "poster": "https://media.themoviedb.org/t/p/w500/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/mLyW3UTgi2lsMdtueYODcfAB9Ku.jpg",
            "genres": ["Comedy"],
            "firstAirDate": "2005-03-24",
            "rating": 8.5,
            "popularity": 78,
            "overview": "An awkward workplace mockumentary turns a paper company into one of TV's most quotable offices.",
            "mediaType": "tv",
        },
        {
            "tmdbId": 60574,
            "title": "Peaky Blinders",
            "originalTitle": "Peaky Blinders",
            "poster": "https://media.themoviedb.org/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/wiE9doxiLwq3WCGamDIOb2PqBqc.jpg",
            "genres": ["Crime", "Drama"],
            "firstAirDate": "2013-09-12",
            "rating": 8.5,
            "popularity": 77,
            "overview": "Tommy Shelby builds a criminal empire in postwar Birmingham with ambition and brutality.",
            "mediaType": "tv",
        },
        {
            "tmdbId": 1398,
            "title": "The Sopranos",
            "originalTitle": "The Sopranos",
            "poster": "https://media.themoviedb.org/t/p/w500/rTc7ZXdroqjkKivFPvCPX0Ru7uw.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/lNpkvX2s8LGB0mjGODMT4o6Up7j.jpg",
            "genres": ["Crime", "Drama"],
            "firstAirDate": "1999-01-10",
            "rating": 8.7,
            "popularity": 73,
            "overview": "A mob boss balances crime-family leadership with panic attacks and therapy.",
            "mediaType": "tv",
        },
        {
            "tmdbId": 1418,
            "title": "The Big Bang Theory",
            "originalTitle": "The Big Bang Theory",
            "poster": "https://media.themoviedb.org/t/p/w500/an3uTx1P0XgHPylgfPV6W7yxKAo.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/gMqQY6SwuhKg1LvmiTxKX6YrINr.jpg",
            "genres": ["Comedy"],
            "firstAirDate": "2007-09-24",
            "rating": 7.9,
            "popularity": 71,
            "overview": "A group of brilliant but socially chaotic friends stumble through work, love, and fandom.",
            "mediaType": "tv",
        },
        {
            "tmdbId": 42009,
            "title": "Black Mirror",
            "originalTitle": "Black Mirror",
            "poster": "https://media.themoviedb.org/t/p/w500/seN6rRfN0I6n8iDXjlSMk1QjNcq.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/dg3OindVAGZBjlT3xYKqIAdukPL.jpg",
            "genres": ["Drama", "Sci-Fi", "Thriller"],
            "firstAirDate": "2011-12-04",
            "rating": 8.3,
            "popularity": 70,
            "overview": "Standalone stories explore the dark edge of technology, media, and human behavior.",
            "mediaType": "tv",
        },
        {
            "tmdbId": 456,
            "title": "The Simpsons",
            "originalTitle": "The Simpsons",
            "poster": "https://media.themoviedb.org/t/p/w500/uWpG7GqfKGQqX4YMAo3nv5OrglV.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/jIArNHIekrCSVgdMbKPAXpPY03Y.jpg",
            "genres": ["Animation", "Comedy"],
            "firstAirDate": "1989-12-17",
            "rating": 8.0,
            "popularity": 75,
            "overview": "Springfield's favorite family continues to satirize everyday life across generations.",
            "mediaType": "tv",
        },
        {
            "tmdbId": 119051,
            "title": "Wednesday",
            "originalTitle": "Wednesday",
            "poster": "https://media.themoviedb.org/t/p/w500/36xXlhEpQqVVPuiZhfoQuaY4OlA.jpg",
            "backdrop": "https://media.themoviedb.org/t/p/w780/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
            "genres": ["Comedy", "Fantasy", "Mystery"],
            "firstAirDate": "2022-11-23",
            "rating": 8.0,
            "popularity": 80,
            "overview": "Wednesday Addams investigates a supernatural mystery while mastering life at Nevermore.",
            "mediaType": "tv",
        },
    ]
)

BLURAY_DEALS = [
    {"movieId": 693134, "title": "Dune: Part Two", "format": "4K UHD", "retailer": "Amazon", "price": 24.99},
    {"movieId": 872585, "title": "Oppenheimer", "format": "4K Steelbook", "retailer": "Best Buy", "price": 31.99},
    {"movieId": 575265, "title": "Mission: Impossible - The Final Reckoning", "format": "Blu-ray", "retailer": "Walmart", "price": 19.99},
    {"movieId": 1022789, "title": "Inside Out 2", "format": "4K UHD", "retailer": "Target", "price": 22.99},
    {"movieId": 912649, "title": "Venom: The Last Dance", "format": "Blu-ray", "retailer": "Amazon", "price": 17.99},
]


def movie_year(movie: dict) -> int:
    return int(movie["releaseDate"][:4])


def find_movie(movie_id: int) -> dict | None:
    return next((movie for movie in MOVIES if movie["tmdbId"] == movie_id), None)


def search_movies(query: str) -> list[dict]:
    normalized = query.lower()
    return [
        movie for movie in MOVIES
        if normalized in movie["title"].lower()
        or any(normalized in genre.lower() for genre in movie["genres"])
    ]


def find_tv_show(series_id: int) -> dict | None:
    return next((show for show in TV_SHOWS if show["tmdbId"] == series_id), None)


def search_tv_shows(query: str) -> list[dict]:
    normalized = query.lower()
    return [
        show for show in TV_SHOWS
        if normalized in show["title"].lower()
        or any(normalized in genre.lower() for genre in show["genres"])
    ]


def filter_movies(
    genre: str | None = None,
    year: int | None = None,
    min_rating: float | None = None,
    min_popularity: float | None = None,
    streaming: str | None = None,
    bluray_available: bool | None = None,
) -> list[dict]:
    movies = MOVIES
    if genre:
        movies = [movie for movie in movies if genre.lower() in [item.lower() for item in movie["genres"]]]
    if year:
        movies = [movie for movie in movies if movie_year(movie) == year]
    if min_rating is not None:
        movies = [movie for movie in movies if movie["rating"] >= min_rating]
    if min_popularity is not None:
        movies = [movie for movie in movies if movie["popularity"] >= min_popularity]
    if streaming:
        movies = [movie for movie in movies if streaming.lower() in [item.lower() for item in movie["streaming"]]]
    if bluray_available is not None:
        movies = [movie for movie in movies if movie["blurayAvailable"] is bluray_available]
    return movies


def build_homepage_sections() -> dict:
    current_year = datetime.now(timezone.utc).year
    today = datetime.now(timezone.utc).date()
    top_this_year = sorted(
        [movie for movie in MOVIES if movie_year(movie) >= current_year - 1],
        key=lambda item: item["rating"],
        reverse=True,
    )[:8]
    trending = sorted(MOVIES, key=lambda item: item["popularity"], reverse=True)[:8]
    popular_movies = sorted(MOVIES, key=lambda item: item["popularity"], reverse=True)[:8]
    top_rated_movies = sorted(MOVIES, key=lambda item: item["rating"], reverse=True)[:8]
    recent_theatrical = sorted(
        [
            movie for movie in MOVIES
            if 0 <= (today - datetime.fromisoformat(movie["releaseDate"]).date()).days <= 120
        ],
        key=lambda item: (item["releaseDate"], item["popularity"]),
        reverse=True,
    )[:8]
    upcoming = sorted(
        [movie for movie in MOVIES if datetime.fromisoformat(movie["releaseDate"]).date() >= today],
        key=lambda item: (item["releaseDate"], -item["popularity"]),
    )[:8]
    genre_groups = {
        genre: [movie for movie in MOVIES if genre in movie["genres"]][:8]
        for genre in ["Action", "Drama", "Sci-Fi", "Comedy", "Family"]
    }
    recommended = sorted(MOVIES, key=lambda item: (item["rating"], item["popularity"]), reverse=True)[:8]
    tv_trending = sorted(TV_SHOWS, key=lambda item: item["popularity"], reverse=True)[:8]
    tv_popular = sorted(TV_SHOWS, key=lambda item: item["rating"], reverse=True)[:8]
    return {
        "topMoviesThisYear": top_this_year,
        "trendingNow": trending,
        "popularMovies": popular_movies,
        "topRatedMovies": top_rated_movies,
        "nowPlaying": recent_theatrical,
        "upcomingMovies": upcoming,
        "popularByGenre": genre_groups,
        "recommendedForYou": recommended,
        "tvTrending": tv_trending,
        "tvPopular": tv_popular,
    }


def movie_category_fallback(category: str) -> list[dict]:
    sections = build_homepage_sections()
    category_map = {
        "popular": sections["popularMovies"],
        "top_rated": sections["topRatedMovies"],
        "now_playing": sections["nowPlaying"],
    }
    return category_map.get(category, sections["popularMovies"])


def generate_price_history(movie_id: int) -> list[dict]:
    base_prices = [34.99, 32.99, 29.99, 27.99, 25.99, 24.99, 28.99, 23.99, 21.99, 24.49]
    start_date = datetime.now(timezone.utc) - timedelta(days=90)
    return [
        {
            "movieId": movie_id,
            "format": "4K UHD",
            "retailer": "Amazon",
            "price": round(price - ((movie_id % 7) * 0.35), 2),
            "date": start_date + timedelta(days=index * 10),
        }
        for index, price in enumerate(base_prices)
    ]
